title: Srikar Paida
author: thesrikarpaida
subtitle: The Normal Human

url: "https://thesrikarpaida.github.io"


footer_only_homepage: true
footer_url: "https://github.com/thesrikarpaida"
footer_text: "My GitHub Profile"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   absolute-link: "https://thesrikarpaida.github.io/resume.pdf"
